sonar.projectKey=$CI_PROJECT_NAME
sonar.sources=app
sonar.tests=tests
sonar.inclusions=app/**/*
sonar.python.coverage.reportPaths=coverage-reports/coverage.xml
sonar.python.xunit.reportPath=xunit-reports/xunit-result.xml
sonar.coverage.exclusions=tests/**/*,__pycache__/**,venv/**